name: 'Test All'
on:
  - workflow_dispatch
jobs:
  test:
    uses: ./.github/workflows/main.yml
    with:
      mode: '["test"]'
      emacs-package: '["emacs-nox"]'
      org-branch: '[
        "release_9.4",
        "main"
      ]'
      python-version: '[
        "2.x",
        "3.x"
      ]'
